version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - back-tier

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
