version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - back-tier

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    networks:
      - back-tier

  tor1:
    image: dockage/tor-privoxy:latest
    ports:
      - "9010:9050" # Tor proxy
      - "9011:9051" # Tor control port
    networks:
      - back-tier
  tor2:
    image: dockage/tor-privoxy:latest
    ports:
      - "9020:9050" # Tor proxy
      - "9021:9051" # Tor control port
    networks:
      - back-tier

  tor3:
    image: dockage/tor-privoxy:latest
    ports:
      - "9030:9050" # Tor proxy
      - "9031:9051" # Tor control port
    networks:
      - back-tier

  tor4:
    image: dockage/tor-privoxy:latest
    ports:
      - "9040:9050" # Tor proxy
      - "9041:9051" # Tor control port
    networks:
      - back-tier

  tor5:
    image: dockage/tor-privoxy:latest
    ports:
      - "9050:9050" # Tor proxy
      - "9051:9051" # Tor control port
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
